ALGORITMO: "Cálculo idade"
DESCRIÇÃO: Calcula idade com base em ano atuel e ano de nascimento.
-------------------------------------------------------


Var
   ano_atual, Ano_nasc, idade : inteiro


Inicio
      Escreva("Em que ano estamos?")
      Leia(ano_atual)
      Escreva("Em que ano nasceu?")
      Leia(ano_nasc)
      idade <- ano_atual - ano_nasc
      Escreva("A idade é ", idade)


Fimalgoritmo